### ISSUE TITLE
Random page may be unauthorised

### ISSUE THREAD

**Issue by no10staples** [getgrav/grav-plugin-random#8]
The page collection that the random plugin chooses from includes pages that the user is not necessarily authorised to view. For example:
* In ``` user.yaml ```, ``` access.area.a: false ```, or no access settings at all
* In ``` item.md ```, ``` access.area.a: true ```

The access settings are ignored when choosing the random page which means the user is just presented with the "you do not have access" page.

**Comment by rhukster** [comment]
That's true, you could get an access denied upon visiting the page..However, the random plugin is really more a test plugin than anything else.  I don't know of anyone that actually uses it :)

You can certainly build your own logic in your own plugin to do more sophisticated things.
